include:
  - project: "gnome/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1

.flatpak-local:
  variables:
    MANIFEST_PATH: "build-aux/flatpak/org.gnome.Decibels.json"
    BUNDLE: "org.gnome.Decibels.Devel.flatpak"
    FLATPAK_MODULE: "decibels"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    APP_ID: "org.gnome.Decibels.Devel"
  before_script:
    - flatpak --user remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
    - flatpak --user install -y flathub-beta org.freedesktop.Sdk.Extension.node18//24.08beta org.freedesktop.Sdk.Extension.typescript//24.08beta

flatpak@x86_64:
  extends:
    - .flatpak@x86_64
    - .flatpak-local

flatpak@aarch64:
  extends:
    - .flatpak@aarch64
    - .flatpak-local

# Publish to nightly repo
nightly@x86_64:
  extends: ".publish_nightly"
  stage: deploy
  dependencies:
    - flatpak@x86_64

nightly@aarch64:
  extends: ".publish_nightly"
  stage: deploy
  dependencies:
    - flatpak@aarch64

eslint:
  image: quay.io/fedora/fedora:latest

  variables:
    LINT_LOG: "eslint-report.txt"
  script:
    - sudo dnf install -y npm
    - npm install
    - npx eslint -o $LINT_LOG --no-color src || { cat $LINT_LOG; false; }
  artifacts:
    paths:
      - ${LINT_LOG}
    when: on_failure
